=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'cgi'

module DatadogAPIClient::V1
  class IPRangesAPI
    attr_accessor :api_client

    def initialize(api_client = DatadogAPIClient::APIClient.default)
      @api_client = api_client
    end

    # List IP Ranges.
    #
    # @see #get_ip_ranges_with_http_info
    def get_ip_ranges(opts = {})
      data, _status_code, _headers = get_ip_ranges_with_http_info(opts)
      data
    end

    # List IP Ranges.
    #
    # Get information about Datadog IP ranges.
    #
    # @param opts [Hash] the optional parameters
    # @return [Array<(IPRanges, Integer, Hash)>] IPRanges data, response status code and response headers
    def get_ip_ranges_with_http_info(opts = {})

      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: IPRangesAPI.get_ip_ranges ...'
      end
      # resource path
      local_var_path = '/'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'IPRanges'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = op