=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The metadata associated with a request.
  class AuditLogsResponseMetadata
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Time elapsed in milliseconds.
    attr_accessor :elapsed

    # Paging attributes.
    attr_accessor :page

    # The identifier of the request.
    attr_accessor :request_id

    # The status of the response.
    attr_accessor :status

    # A list of warnings (non-fatal errors) encountered. Partial results may return if
    # warnings are present in the response.
    attr_accessor :warnings

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'elapsed' => :'elapsed',
        :'page' => :'page',
        :'request_id' => :'request_id',
        :'status' => :'status',
        :'warnings' => :'warnings'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'elapsed' => :'Integer',
        :'page' => :'Audit