=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # A bucket value, can either be a timeseries or a single value.
  module CIAppAggregateBucketValue
    class << self
      include BaseOneOfModel
      include BaseOneOfModelNoDiscriminator

      # List of class defined in oneOf (OpenAPI v3)
      def openapi_one_of
        [
          :'String',
          :'Float',
          :'Array<CIAppAggregateBucketValueTimeseriesPoint>'
        ]
      end
      # Builds the object
      # @param data [Mixed] Data to be matched against the list of oneOf items
      # @return [Object] Returns the model or 