=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The incident's relationships from a response.
  class IncidentResponseRelationships
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # A relationship reference for attachments.
    attr_accessor :attachments

    # Relationship to user.
    attr_accessor :commander_user

    # Relationship to user.
    attr_accessor :created_by_user

    # A relationship reference for multiple integration metadata objects.
    attr_accessor :integrations

    # Relationship to user.
    attr_accessor :last_modified_by_user

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'attachments' => :'attachments',
        :'commander_user' => :'commander_user',
        :'created_by_user' => :'created_by_user',
        :'integrations' => :'integrations',
        :'last_modifi