=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # The object sent with the request to retrieve a list of logs from your organization.
  class LogsAggregateRequest
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # The list of metrics or timeseries to compute for the retrieved buckets.
    attr_accessor :compute

    # The search and filter query settings
    attr_accessor :filter

    # The rules for the group by
    attr_accessor :group_by

    # Global query options that are used during the query.
    # Note: You should only supply timezone or time offset but not both otherwise the query will fail.
    attr_accessor :options

    # Paging settings
    attr_accessor :page

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'compute' => :'compute',
        :'filter' => :'filter',
        :'group_by' => :'group_by',
        :'options' => :'options',
        :'page' => :'page'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'compute' => :'Array<LogsCompute>',
        :'filter' => :'LogsQueryFil