=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Query for matching rule on signals.
  class SecurityMonitoringSignalRuleQuery
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # The aggregation type.
    attr_accessor :aggregation

    # Fields to group by.
    attr_accessor :correlated_by_fields

    # Index of the rule query used to retrieve the correlated field.
    attr_reader :correlated_query_index

    # Group of target fields to aggregate over.
    attr_accessor :metrics

    # Name of the query.
    attr_accessor :name

    # Rule ID to match on signals.
    attr_reader :rule_id

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'aggregation' => :'aggregation',
        :'correlated_by_fields' => :'correlatedByFields',
        :'correlated_query_index' => :'correlatedQueryIndex',
        :'metrics' => :'metrics',
        :'name' => :