=begin
#Datadog API V2 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V2
  # Service definition V2 for providing service metadata and integrations.
  class ServiceDefinitionV2
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # A list of contacts related to the services.
    attr_accessor :contacts

    # Unique identifier of the service. Must be unique across all services and is used to match with a service in Datadog.
    attr_reader :dd_service

    # Experimental feature. A Team handle that matches a Team in the Datadog Teams product.
    attr_accessor :dd_team

    # A list of documentation related to the services.
    attr_accessor :docs

    # Extensions to V2 schema.
    attr_accessor :extensions

    # Third party integrations that Datadog supports.
    attr_accessor :integrations

    # A list of links related to the services.
    attr_accessor :links

    # A list of code repositories related to the services.
    attr_accessor :repos

    # Schema version being used.
    attr_reader :schema_version

    # A set of custom tags.
    attr_accessor :tags

    # Team that owns the service.
    attr_accessor :team

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'contacts' => :'contacts',
        :'dd_service' => :'dd-service',
        :'dd_team' => :'dd-team',
        :'docs' => :'docs',
        :'extensions' => :'extensions',
        :'integrations' => :'integrations',
        :'links' => :'links',
        :'repos' => :'repos',
        :'schema_version' => :'schema-version',
        :'tags' => :'tags',
        :'team' => :'team'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'contacts' => :'Array<ServiceDefinitionV2Contact>',
        :'dd_service' => :'String',
        :'dd_team' => :'String',
        :'docs' => :'Array<ServiceDefinitionV2Doc>',
        :'extensions' => :'Hash<String, Object>',
        :'integrations' => :'ServiceDefinitionV2Integrations',
        :'links' => :'Array<ServiceDefinitionV2Link>',
        :'repos' => :'Array<ServiceDefinitionV2Repo>',
        :'schema_version' => :'ServiceDefinitionV2Version',
        :'tags' => :'Array<String>',
        :'team' => :'String'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DatadogAPIClient::V2::ServiceDefinitionV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DatadogAPIClient::V2::ServiceDefinitionV2`. Please check the name to ma