=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://openapi-generator.tech

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'spec_helper'

describe DatadogAPIClient::APIClient do
  context 'initialization' do
    context 'URL stuff' do
      context 'host' do
        it 'removes http from host' do
          DatadogAPIClient.configure { |c| c.host = 'http://example.com' }
          expect(DatadogAPIClient::Configuration.default.host).to eq('example.com')
        end

        it 'removes https from host' do
          DatadogAPIClient.configure { |c| c.host = 'https://wookiee.com' }
          expect(DatadogAPIClient::APIClient.default.config.host).to eq('wookiee.com')
        end

        it 'removes trailing path from host' do
          DatadogAPIClient.configure { |c| c.host = 'hobo.com/v4' }
          expect(DatadogAPIClient::Configuration.default.host).to eq('hobo.com')
        end
      end

      context 'base_path' do
        it "prepends a slash to base_path" do
          DatadogAPIClient.configure { |c| c.base_path = 'v4/dog' }
          expect(DatadogAPIClient::Configuration.default.base_path).to eq('/v4/dog')
        end

        it "doesn't prepend a slash if one is already there" do
          DatadogAPIClient.configure { |c| c.base_path = '/v4/dog' }
          expect(DatadogAPIClient::Configuration.default.base_path).to eq('/v4/dog')
        end

        it "ends up as a blank string if nil" do
          DatadogAPIClient.configure { |c| c.base_path = nil }
          expect(DatadogAPIClient::Configuration.default.base_path).to eq('')
        end
      end
    end
  end

  describe 'timeout in #build_request' do
    let(:config) { DatadogAPIClient::Configuration.new }
    let(:api_client) { DatadogAPIClient::APIClient.new(config) }

    it 'defaults to nil' do
      expect(DatadogAPIClient::Configuration.default.timeout).to eq(nil)
      expect(config.timeout).to eq(nil)

      request = api_client.build_request(Net::HTTP::Get, '/test')
      expect(request.options[:timeout]).to eq(nil)
    end

    it 'can be customized' do
      config.timeout = 100
      request = api_client.build_request(Net::HTTP::Get, '/test')
      expect(request.options[:timeout]).to eq(100)
    end
  end

  describe '#deserialize' do
    it "handles Array<Integer>" do
      api_client = DatadogAPIClient::APIClient.new
      headers = { 'Content-Type' => 'application/json' }
      response = double('response', headers: headers, body: '[12, 34]')
      data = api_client.deserialize("V1", response, 'Array<Integer>')
      expect(data).to be_instance_of(Array)
      expect(data).to eq([12, 34])
    end

    it 'handles Array<Array<Integer>>' do
      api_client = DatadogAPIClient::APIClient.new
      headers = { 'Content-Type' => 'application/json' }
      response = double('response', headers: headers, body: '[[12, 34], [56]]')
      data = api_client.deserialize("V1", response, 'Array<Array<Integer>>')
      expect(data).to be_instance_of(Array)
      expect(data).to eq([[12, 34], [56]])
    end

    it 'handles Hash<String, String>' do
      api_client = DatadogAPIClient::APIClient.new
      headers = { 'Content-Type' => 'application/json' }
      response = double('response', headers: headers, body: '{"message": "Hello"}')
      data = api_client.deserialize("V1", response, 'Hash<String, String>')
      expect(data).to be_instance_of(Hash)
      expect(data).to eq(:message => 'Hello')
    end
  end

  describe "#object_to_hash" do
    it 'ignores nils and includes empty arrays' do
      # uncomment below to test object_to_hash for model
      # api_client = DatadogAPIClient::APIClient.new
      # _model = DatadogAPIClient::ModelName.new
      # update the model attribute below
      # _model.id = 1
      # update the expected value (hash) below
      # expected = {id: 1, name: '', tags: []}
      # expect(api_client.object_to_hash(_model)).to eq(expected)
    end
  end

  describe '#build_collection_param' do
    let(:param) { ['aa', 'bb', 'cc'] }
    let(:api_client) { DatadogAPIClient::APIClient.new }

    it 'works for csv' do
      expect(api_client.build_collection_param(param, :csv)).to eq('aa,bb,cc')
    end

    it 'works for ssv' do
      expect(api_client.build_collection_param(param, :ssv)).to eq('aa bb cc')
    end

    it 'works for tsv' do
      expect(api_client.build_collection_param(param, :tsv)).to eq("aa\tbb\tcc")
    end

    it 'works for pipes' do
      expect(api_client.build_collection_param(param, :pipes)).to eq('aa|bb|cc')
    end

    it 'works for multi' do
      expect(api_client.build_collection_param(param, :multi)).to eq(['aa', 'bb', 'cc'])
    end

    it 'fails for invalid collection format' do
      expect { api_client.build_collection_param(param, :INVALID) }.to raise_error(RuntimeError, 'u