=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The downtime object definition of the active child for the original parent recurring downtime. This
  # field will only exist on recurring downtimes.
  class DowntimeChild
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # If a scheduled downtime currently exists.
    attr_accessor :active

    # If a scheduled downtime is canceled.
    attr_accessor :canceled

    # User ID of the downtime creator.
    attr_reader :creator_id

    # If a downtime has been disabled.
    attr_accessor :disabled

    # `0` for a downtime applied on `*` or all,
    # `1` when the downtime is only scoped to hosts,
    # or `2` when the downtime is scoped to anything but hosts.
    attr_reader :downtime_type

    # POSIX timestamp to end the downtime. If not provided,
    # the downtime is in effect indefinitely until you cancel it.
    attr_accessor :_end

    # The downtime ID.
   