=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The groups widget allows you to keep similar graphs together on your timeboard. Each group has a custom header, can hold one to many graphs, and is collapsible.
  class GroupWidgetDefinition
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Background color of the group title.
    attr_accessor :background_color

    # URL of image to display as a banner for the group.
    attr_accessor :banner_img

    # Layout type of the group.
    attr_reader :layout_type

    # Whether to show the title or not.
    attr_accessor :show_title

    # Title of the widget.
    attr_accessor :title

    # How to align the text on the widget.
    attr_accessor :title_align

    # Type of the group widget.
    attr_reader :type

    # List of widget groups.
    attr_reader :widgets

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'background_color' => :'background_color',
        :'banner_img' => :'banner_img',
        :'layout_type' => :'layout_type',
        :'show_title' => :'show_title',
        :'title' => :'title',
        :'title_align' => 