=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The host map widget graphs any metric across your hosts using the same visualization available from the main Host Map page.
  class HostMapWidgetDefinition
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # List of custom links.
    attr_accessor :custom_links

    # List of tag prefixes to group by.
    attr_accessor :group

    # Whether to show the hosts that don’t fit in a group.
    attr_accessor :no_group_hosts

    # Whether to show the hosts with no metrics.
    attr_accessor :no_metric_hosts

    # Which type of node to use in the map.
    attr_accessor :node_type

    # Notes on the title.
    attr_accessor :notes

    # List of definitions.
    attr_reader :requests

    # List of tags used to filter the map.
    attr_accessor :scope

    # The style to apply to the widget.
    attr_accessor :style

    # Title of the widget.
    attr_accessor :title

    # How to align the text on the widget.
    attr_accessor :title_align

    # Size of the title.
    attr_accessor :title_size

    # Type of the host map widget.
    attr_reader :type

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'custom_links' => :'custom_links',
        :'group' => :'group',
        :'no_group_hosts' => :'no_group_hosts',
        :'no_metric_hosts' => :'no_metric_hosts',
        :'node_type' => :'node_type',
        :'notes' => :'notes',
        :'requests' => :'requests',
        :'scope' => :'scope',
        :'style' => :'style',
        :'title' => :'title',
        :'title_align' => :'title_align',
        :'title_size' => :'title_size',
        :'type' => :'type'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'custom_links' => :'Array<WidgetCustomLink>',
        :'group' => :'Array<String>',
        :'no_group_hos