=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The usage for one set of tags for one hour.
  class HourlyUsageAttributionBody
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # The hour for the usage.
    attr_accessor :hour

    # The name of the organization.
    attr_accessor :org_name

    # The organization public ID.
    attr_accessor :public_id

    # The source of the usage attribution tag configuration and the selected tags in the format of `<source_org_name>:::<selected tag 1>///<selected tag 2>///<selected tag 3>`.
    attr_accessor :tag_config_source

    # Tag keys and values.
    #
    # A `null` value here means that the requested tag breakdown cannot be applied because it does not match the [tags
    # configured for usage attribution](https://docs.datadoghq.com/account_management/billing/usage_attribution/#getting-started).
    # In this scenario the API returns the total usage, not broken down by tags.
    attr_accessor :tags

    # Total product usage for the given tags within the hour.
    attr_accessor :total_usage_sum

    # Shows the most recent hour in the current month for all organizations where usages are calculated.
    attr_accessor :updated_at

    # Supported products for hourly usage attribution requests.
    attr_accessor :usage_type

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'hour' => :'hour',
        :'org_name' => :'org_name',
        :'public_id' => :'public_id',
        :'tag_config_source' => :'tag_config_source',
        :'tags' => :'tags',
        :'total_usage_sum' => :'total_usage_sum',
        :'updated_at' => :'updated_at',
        :'usage_type' => :'usage_type'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.ope