=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Represents the index exclusion filter object from configuration API.
  class LogsExclusion
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Exclusion filter is defined by a query, a sampling rule, and a active/inactive toggle.
    attr_accessor :filter

    # Whether or not the exclusion filter is active.
    attr_accessor :is_enabled

    # Name of the index exclusion filter.
    attr_reader :name

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'filter' => :'filter',
        :'is_enabled' => :'is_enabled',
        :'name' => :'name'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'filter' => :'LogsExclusionFilter',
        :'is_enabled' => :'Boolean',
        :'name' => :'String'
      }