=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Response Object that includes your query and the list of metrics retrieved.
  class MetricsQueryResponse
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Message indicating the errors if status is not `ok`.
    attr_accessor :error

    # Start of requested time window, milliseconds since Unix epoch.
    attr_accessor :from_date

    # List of tag keys on which to group.
    attr_accessor :group_by

    # Message indicating `success` if status is `ok`.
    attr_accessor :message

    # Query string
    attr_accessor :query

    # Type of response.
    attr_accessor :res_type

    # List of timeseries queried.
    attr_accessor :series

    # Status of the query.
    attr_accessor :status

    # End of requested time window, milliseconds since Unix epoch.
    attr_accessor :to_date

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'error' => :'error',
        :'from_date' => :'from_date',
        :'group_by' => :'group_by',
        :'message' => :'message',
        :'query' => :'query',
        :'res_type' => :'res_type',
        :'series' => :'series',
        :'status' => :'status',
        :'to_date' => :'to_date'
      }
    end

    # Attribute type mapping.
    # @!visibi