=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Usage Summary by tag for a given organization.
  class MonthlyUsageAttributionBody
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Datetime in ISO-8601 format, UTC, precise to month: [YYYY-MM].
    attr_accessor :month

    # The name of the organization.
    attr_accessor :org_name

    # The organization public ID.
    attr_accessor :public_id

    # The source of the usage attribution tag configuration and the selected tags in the format `<source_org_name>:::<selected tag 1>///<selected tag 2>///<selected tag 3>`.
    attr_accessor :tag_config_source

    # Tag keys and values.
    #
    # A `null` value here means that the requested tag breakdown cannot be applied because it does not match the [tags
    # configured for usage attribution](https://docs.datadoghq.com/account_management/billing/usage_attribution/#getting-started).
    # In this scenario the API returns the total usage, not broken down by tags.
    attr_accessor :tags

    # Datetime of the most recent update to the usage values.
    attr_accessor :updated_at

    # Fields in Usage Summary by tag(s).
    attr_accessor :values

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'month' => :'month',
        :'org_name' => :'org_name',
        :'public_id' => :'public_id',
        :'tag_config_source' => :'tag_config_source',
        :'tags' => :'tags',
        :'updated_at' => :'updated_at',
        :'values' => :'values'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'month' => :'Time',
        :'org_name' => :'String',
        :'public_id' => :'String',
        :'tag_config_source' => :'String',
        :'tags' => :'Hash<String, Array<String>>',
        :'updated_at' => :'Time',
        :'values' => :'MonthlyUsageAttributionValues'
      }
    end

    # Initializes the object
    # @param attributes [Hash] Model attributes in the form of hash
    # @!visibility private
    def initiali