=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Create, edit, and manage organizations.
  class Organization
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # A JSON array of billing type.
    attr_accessor :billing

    # Date of the organization creation.
    attr_accessor :created

    # Description of the organization.
    attr_accessor :description

    # The name of the new child-organization, limited to 32 characters.
    attr_reader :name

    # The `public_id` of the organization you are operating within.
    attr_accessor :public_id

    # A JSON array of settings.
    attr_accessor :settings

    # Subscription definition.
    attr_accessor :subscription

    # Only available for MSP customers. Allows child organizations to be created on a trial plan.
    attr_accessor :trial

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'billing' => :'billing',
        :'created' => :'created',
        :'description' => :'description',
        :'name' => :'name',
     