=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Facets
  class SearchSLOResponseDataAttributesFacets
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # All tags associated with an SLO.
    attr_accessor :all_tags

    # Creator of an SLO.
    attr_accessor :creator_name

    # Tags with the `env` tag key.
    attr_accessor :env_tags

    # Tags with the `service` tag key.
    attr_accessor :service_tags

    # Type of SLO.
    attr_accessor :slo_type

    # SLO Target
    attr_accessor :target

    # Tags with the `team` tag key.
    attr_accessor :team_tags

    # Timeframes of SLOs.
    attr_accessor :timeframe

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'all_tags' => :'all_tags',
        :'creator_name' => :'creator_name',
        :'env_tags' => :'env_tags',
        :'service_tags' => :'service_tags',
        :'slo_type' => :'slo_type',
        :'target' => :'target',
        :'team_tags' => :'team_tags',
        :'timeframe' => :'timeframe'
      }
    end

    # Attribute type mapping.
    # @!visibility private
    def self.openapi_types
      {
        :'all_tags' => :'Array<SearchSLOResponseDataAttributesFacetsObjectStri