=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # A service level objective ID and attributes.
  class SearchServiceLevelObjectiveData
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # A service level objective object includes a service level indicator, thresholds
    # for one or more timeframes, and metadata (`name`, `description`, and `tags`).
    attr_accessor :attributes

    # A unique identifier for the service level objective object.
    #
    # Always included in service level objective responses.
    attr_accessor :id

    # The type of the object, must be `slo`.
    attr_acces