=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Overall status of the SLO by timeframes.
  class SLOOverallStatuses
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Error message if SLO status or error budget could not be calculated.
    attr_accessor :error

    # Remaining error budget of the SLO in percentage.
    attr_accessor :error_budget_remaining

    # timestamp (UNIX time in seconds) of when the SLO status and error budget
    # were calculated.
    attr_accessor :indexed_at

    # Error budget remaining for an SLO.
    attr_accessor :raw_error_budget_remaining

    # The amount of decimal places the SLI value is accurate to.
    attr_accessor :span_precision

    # State of the SLO.
    attr_accessor :state

    # The status of the SLO.
    attr_accessor :status

    # The target of the SLO.
    attr_