=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The field to sort by.
  class UsageAttributionSort
    include BaseEnumModel

    API_PERCENTAGE = "api_percentage".freeze
    SNMP_USAGE = "snmp_usage".freeze
    APM_HOST_USAGE = "apm_host_usage".freeze
    API_USAGE = "api_usage".freeze
    APPSEC_USAGE = "appsec_usage".freeze
    APPSEC_PERCENTAGE = "appsec_percentage".freeze
    CONTAINER_USAGE = "container_usage".freeze
    CUSTOM_TIMESERIES_PERCENTAGE = "custom_timeseries_percentage".freeze
    CONTAINER_PERCENTAGE = "container_percentage".freeze
    APM_HOST_PERCENTAGE = "apm_host_percentage".freeze
    NPM_HOST_PERCENTAGE = "npm_host_percentage".freeze
    BROWSER_PERCENTAGE = "browser_percentage".freeze
    BROWSER_USAGE = "browser_usage".freeze
    INFRA_HOST_PERCENTAGE = "infra_host_percentage".freeze
    SNMP_PERCENTAGE = 