=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Global hourly report of all data billed by Datadog for a given organization.
  class UsageSummaryDateOrg
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # Shows the 99th percentile of all agent hosts over all hours in the current date for the given org.
    attr_accessor :agent_host_top99p

    # Shows the 99th percentile of all Azure app services using APM over all hours in the current date for the given org.
    attr_accessor :apm_azure_app_service_host_top99p

    # Shows the average of all APM ECS Fargate tasks over all hours in the current months for the given org.
    attr_accessor :apm_fargate_count_avg

    # Shows the 99th percentile of all distinct APM hosts over all hours in the current date for the given org.
    attr_accessor :apm_host_top99p

    # Shows the average of all Application Security Monitoring ECS Fargate tasks over all hours in the current months for the given org.
    attr_accessor :appsec_fargate_count_avg

    # Shows the sum of all audit logs lines indexed over all hours in the current date for the given org.
    attr_accessor :audit_logs_lines_indexed_sum

    # Shows whether Audit Trail is enabled for the current date for the given org.
    attr_accessor :audit_trail_enabled_hwm

    # The average profiled task count for Fargate Profiling.
    attr_accessor :avg_profiled_fargate_tasks

    # Shows the 99th percentile of all AWS hosts over all hours in the current date for the given org.
    attr_accessor :aws_host_top99p

    # Shows the sum of all AWS Lambda invocations over all hours in the current date for the given org.
    attr_accessor :aws_lambda_func_count

    # Shows the sum of all AWS Lambda invocations over all hours in the current date for the given org.
    attr_accessor :aws_lambda_invocations_sum

    # Shows the 99th percentile of all Azure app services over all hours in the current date for the given org.
    attr_accessor :azure_app_service_top99p

    # Shows the sum of all log bytes ingested over all hours in the current date for the given org.
    attr_accessor :billable_ingested_bytes_sum

    # Shows the sum of all browser lite sessions over all hours in the current date for the given org.
    attr_accessor :browser_rum_lite_session_count_sum

    # Shows the sum of all browser replay sessions over all hours in the current date for the given org.
    attr_accessor :browser_rum_replay_session_count_sum

    # Shows the sum of all browser RUM units over all hours in the current date for the given org.
    attr_accessor :browser_rum_units_sum

    # Shows the sum of all CI pipeline indexed spans over all hours in the current date for the given org.
    attr_accessor :ci_pipeline_indexed_spans_sum

    # Shows the sum of all CI test indexed spans over all hours in the current date for the given org.
    attr_accessor :ci_test_indexed_spans_sum

    # Shows the high-water mark of all CI visibility pipeline committers over all hours in the current date for the given org.
    attr_accessor :ci_visibility_pipeline_committers_hwm

    # Shows the high-water mark of all CI visibility test committers over all hours in the current date for the given org.
    attr_accessor :ci_visibility_test_committers_hwm

    # Host count average of Cloud Cost Management for the given date and given org.
    attr_accessor :cloud_cost_management_host_count_avg

    # Shows the average of all distinct containers over all hours in the current date for the given org.
    attr_accessor :container_avg

    # Shows the average of containers without the Datadog Agent over all hours in the current date for the given organization.
    attr_accessor :container_excl_agent_avg

    # Shows the high-water mark of all distinct containers over all hours in the current date for the given org.
    attr_accessor :container_hwm

    # Shows the 99th percentile of all Cloud Security Posture Management Azure app services hosts over all hours in the current date for the given org.
    attr_accessor :cspm_aas_host_top99p

    # Shows the 99th percentile of all Cloud Security Posture Management AWS hosts over all hours in the current date for the given org.
    attr_accessor :cspm_aws_host_top99p

    # Shows the 99th percentile of all Cloud Security Posture Management Azure hosts over all hours in the current date for the given org.
    attr_accessor :cspm_azure_host_top99p

    # Shows the average number of Cloud Security Posture Management containers over all hours in the current date for the given org.
    attr_accessor :cspm_container_avg

    # Shows the high-water mark of Cloud Security Posture Management containers over all hours in the current date for the given org.
    attr_accessor :cspm_container_hwm

    # Shows the 99th percentile of all Cloud Security Posture Management GCP hosts over all hours in the current date for the given org.
    attr_accessor :cspm_gcp_host_top99p

    # Shows the 99th percentile of all Cloud Security Posture Management hosts over all hours in the current date for the given org.
    attr_accessor :cspm_host_top99p

    # Shows the average number of distinct custom metrics over all hours in the current date for the given org.
    attr_accessor :custom_ts_avg

    # Shows the average of all distinct Cloud Workload Security containers over all hours in the current date for the given org.
    attr_accessor :cws_container_count_avg

    # Shows the 99th percentile of all Cloud Workload Security hosts over all hours in the current date for the given org.
    attr_accessor :cws_host_top99p

    # Shows the 99th percentile of all Database Monitoring hosts over all hours in the current month for the given org.
    attr_accessor :dbm_host_top99p_sum

    # Shows the average of all distinct Database Monitoring normalized queries over all hours in the current month for the given org.
    attr_accessor :dbm_queries_avg_sum

    # The average task count for Fargate.
    attr_accessor :fargate_tasks_count_avg

    # Shows the high-water mark of all Fargate tasks over all hours in the current date for the given org.
    attr_accessor :fargate_tasks_count_hwm

    # Shows the 99th percentile of all GCP hosts over all hours in the current date for the given org.
    attr_accessor :gcp_host_top99p

    # Shows the 99th percentile of all Heroku dynos over all hours in the current date for the given org.
    attr_accessor :heroku_host_top99p

    # The organization id.
    attr_accessor :id

    # Shows the high-water mark of incident management monthly active users over all hours in the current date for the given org.
    attr_accessor :incident_management_monthly_active_users_hwm

    # Shows the sum of all log events indexed over all hours in the current date for the given org.
    attr_accessor :indexed_events_count_sum

    # Shows the 99th percentile of all distinct infrastructure hosts over all hours in the current date for the given org.
    attr_accessor :infra_host_top99p

    # Shows the sum of all log bytes ingested over all hours in the current date for the given org.
    attr_accessor :ingested_events_bytes_sum

    # Shows the sum of all IoT devices over all hours in the current date for the given org.
    attr_accessor :iot_device_agg_sum

    # Shows the 99th percentile of all IoT devices over all hours in the current date for the given org.
    attr_accessor :iot_device_top99p_sum

    # Shows the sum of all mobile lite sessions over all hours in the current date for the given org.
    attr_accessor :mobile_rum_lite_session_count_sum

    # Shows the sum of all mobile RUM Sessions on Android over all hours in the current date for the given org.
    attr_accessor :mobile_rum_session_count_android_sum

    # Shows the sum of all mobile RUM Sessions on Flutter over all hours in the current date for the given org.
    attr_accessor :mobile_rum_session_count_flutter_sum

    # Shows the sum of all mobile RUM Sessions on iOS over all hours in the current date for the given org.
    attr_accessor :mobile_rum_session_count_ios_sum

    # Shows the sum of all mobile RUM Sessions on React Native over all hours in the current date for the given org.
    attr_accessor :mobile_rum_session_count_reactnative_sum

    # Shows the sum of all mobile RUM Sessions over all hours in the current date for the given org.
    attr_accessor :mobile_rum_session_count_sum

    # Shows the sum of all mobile RUM units over all hours in the current date for the given org.
    attr_accessor :mobile_rum_units_sum

    # The organization name.
    attr_accessor :name

    # Shows the sum of all Network flows indexed over all hours in the current date for the given org.
    attr_accessor :netflow_indexed_events_count_sum

    # Shows the 99th percentile of all distinct Networks hosts over all hours in the current date for the given org.
    attr_accessor :npm_host_top99p

    # Sum of all observability pipelines bytes processed over all hours in the current date for the given org.
    attr_accessor :observability_pipelines_bytes_processed_sum

    # Sum of all online archived events over all hours in the current date for the given org.
    attr_accessor :online_archive_events_count_sum

    # Shows the 99th percentile of APM hosts reported by the Datadog exporter for the OpenTelemetry Collector over all hours in the current date for the given org.
    attr_accessor :opentelemetry_apm_host_top99p

    # Shows the 99th percentile of all hosts reported by the Datadog exporter for the OpenTelemetry Collector over all hours in the current date for the given org.
    attr_accessor :opentelemetry_host_top99p

    # Shows the 99th percentile of all profiled hosts over all hours in the current date for the given org.
    attr_accessor :profiling_host_top99p

    # The organization public id.
    attr_accessor :public_id

    # The region of the organization.
    attr_accessor :region

    # Shows the sum of all mobile sessions and all browser lite and legacy sessions over all hours in the current date for the given org.
    attr_accessor :rum_browser_and_mobile_session_count

    # Shows the sum of all browser RUM Lite Sessions over all hours in the current date for the given org.
    attr_accessor :rum_session_count_sum

    # Shows the sum of RUM Sessions (browser and mobile) over all hours in the current date for the given org.
    attr_accessor :rum_total_session_count_sum

    # Shows the sum of all browser and mobile RUM units over all hours in the current date for the given org.
    attr_accessor :rum_units_sum

    # Sum of all APM bytes scanned with sensitive data scanner over all hours in the current date for the given org.
    attr_accessor :sds_apm_scanned_bytes_sum

    # Sum of all event stream events bytes scanned with sensitive data scanner over all hours in the current date for the given org.
    attr_accessor :sds_events_scanned_bytes_sum

    # Shows the sum of all bytes scanned of logs usage by the Sensitive Data Scanner over all hours in the current month for the given org.
    attr_accessor :sds_logs_scanned_bytes_sum

    # Sum of all RUM bytes scanned with sensitive data scanner over all hours in the current date for the given org.
    attr_accessor :sds_rum_scanned_bytes_sum

    # Shows the sum of all bytes scanned across all usage types by the Sensitive Data Scanner over all hours in the current month for the given org.
    attr_accessor :sds_total_scanned_bytes_sum

    # Shows the sum of all Synthetic browser tests over all hours in the current date for the given org.
    attr_accessor :synthetics_browser_check_calls_count_sum

    # Shows the sum of all Synthetic API tests over all hours in the current date for the given org.
    attr_accessor :synthetics_check_calls_count_sum

    # Shows the high-water mark of used synthetics parallel testing slots over all hours in the current date for the given org.
    attr_accessor :synthetics_parallel_testing_max_slots_hwm

    # Shows the sum of all Indexed Spans indexed over all hours in the current date for the given org.
    attr_accessor :trace_search_indexed_events_count_sum

    # Shows the sum of all ingested APM span bytes over all hours in the current date for the given org.
    attr_accessor :twol_ingested_events_bytes_sum

    # Shows the 99th percentile of all vSphere hosts over all hours in the current date for the given org.
    attr_accessor :vsphere_host_top99p

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'agent_host_top99p' => :'agent_host_top99p',
        :'apm_azure_app_service_host_top99p' => :'apm_azure_app_service_host_top99p',
        :'apm_fargate_count_avg' => :'apm_fargate_count_avg',
        :'apm_host_top99p' => :'apm_host_top99p',
        :'appsec_fargate_count_avg' => :'appsec_fargate_count_avg',
        :'audit_logs_lines_indexed_sum' => :'audit_logs_lines_indexed_sum',
        :'audit_trail_enabled_hwm' => :'audit_trail_enabled_hwm',
        :'avg_profiled_fargate_tasks' => :'avg_profiled_fargate_tasks',
        :'aws_host_top99p' => :'aws_host_top99p',
        :'aws_lambda_func_count' => :'aws_lambda_func_count',
        :'aws_lambda_invocations_sum' => :'aws_lambda_invocations_sum',
        :'azure_app_service_top99p' => :'azure_app_service_top99p',
        :'billable_ingested_bytes_sum' => :'billable_ingested_bytes_sum',
        :'browser_rum_lite_session_count_sum' => :'browser_rum_lite_session_count_sum',
        :'browser_rum_