=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # The response containing attributes for specified custom reports.
  class UsageSpecifiedCustomReportsAttributes
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # The date the specified custom report was computed.
    attr_accessor :computed_on

    # The ending date of specified custom report.
    attr_accessor :end_date

    # A downloadable file for the specified custom reporting file.
    attr_accessor :location

    # size
    attr_accessor :size

    # The starting date of specified custom report.
    attr_accessor :start_date

    # A list of tags to apply to specified custom reports.
    attr_accessor :tags

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'computed_on' => :'computed_on',
        :'end_date' => :'end_date',
        :'location' => :'location',
        