=begin
#Datadog API V1 Collection

#Collection of all Datadog Public endpoints.

The version of the OpenAPI document: 1.0
Contact: support@datadoghq.com
Generated by: https://github.com/DataDog/datadog-api-client-ruby/tree/master/.generator

 Unless explicitly stated otherwise all files in this repository are licensed under the Apache-2.0 License.
 This product includes software developed at Datadog (https://www.datadoghq.com/).
 Copyright 2020-Present Datadog, Inc.

=end

require 'date'
require 'time'

module DatadogAPIClient::V1
  # Update request of a Webhooks integration object.
  # 
  # *All properties are optional.*
  class WebhooksIntegrationUpdateRequest
    include BaseGenericModel

    # Whether the object has unparsed attributes
    # @!visibility private
    attr_accessor :_unparsed

    # If `null`, uses no header.
    # If given a JSON payload, these will be headers attached to your webhook.
    attr_accessor :custom_headers

    # Encoding type. Can be given either `json` or `form`.
    attr_accessor :encode_as

    # The name of the webhook. It corresponds with `<WEBHOOK_NAME>`.
    # Learn more on how to use it in
    # [monitor notifications](https://docs.datadoghq.com/monitors/notify).
    attr_accessor :name

    # If `null`, uses the default payload.
    # If given a JSON payload, the webhook returns the payload
    # specified by the given payload.
    # [Webhooks variable usage](https://docs.datadoghq.com/integrations/webhooks/#usage).
    attr_accessor :payload

    # URL of the webhook.
    attr_accessor :url

    # Attribute mapping from ruby-style variable name to JSON key.
    # @!visibility private
    def self.attribute_map
      {
        :'custom_hea